// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	OrgID      pgtype.UUID        `json:"org_id"`
	Name       string             `json:"name"`
	KeyHash    string             `json:"key_hash"`
	KeyPrefix  string             `json:"key_prefix"`
	Scopes     []string           `json:"scopes"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Revoked    pgtype.Bool        `json:"revoked"`
}

type AuditLog struct {
	ID            int64              `json:"id"`
	ActorUserID   pgtype.UUID        `json:"actor_user_id"`
	ActorApiKeyID pgtype.UUID        `json:"actor_api_key_id"`
	Action        string             `json:"action"`
	ResourceType  pgtype.Text        `json:"resource_type"`
	ResourceID    pgtype.Text        `json:"resource_id"`
	Metadata      []byte             `json:"metadata"`
	IpHash        pgtype.Text        `json:"ip_hash"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type DockerImage struct {
	ID        uuid.UUID          `json:"id"`
	PackageID uuid.UUID          `json:"package_id"`
	Tag       string             `json:"tag"`
	Digest    string             `json:"digest"`
	EcrUri    string             `json:"ecr_uri"`
	Platform  []string           `json:"platform"`
	SizeBytes pgtype.Int8        `json:"size_bytes"`
	PushedAt  pgtype.Timestamptz `json:"pushed_at"`
}

type DownloadEvent struct {
	ID           pgtype.Int8        `json:"id"`
	FileID       uuid.UUID          `json:"file_id"`
	DownloadedAt pgtype.Timestamptz `json:"downloaded_at"`
	IpHash       pgtype.Text        `json:"ip_hash"`
	UserAgent    pgtype.Text        `json:"user_agent"`
	CountryCode  pgtype.Text        `json:"country_code"`
	Installer    pgtype.Text        `json:"installer"`
}

type OauthIdentity struct {
	ID             uuid.UUID   `json:"id"`
	UserID         uuid.UUID   `json:"user_id"`
	Provider       string      `json:"provider"`
	ProviderUserID string      `json:"provider_user_id"`
	ProviderEmail  pgtype.Text `json:"provider_email"`
}

type OrgMember struct {
	OrgID  uuid.UUID `json:"org_id"`
	UserID uuid.UUID `json:"user_id"`
	Role   string    `json:"role"`
}

type Organization struct {
	ID              uuid.UUID          `json:"id"`
	Name            string             `json:"name"`
	DisplayName     string             `json:"display_name"`
	BillingEmail    pgtype.Text        `json:"billing_email"`
	SsoEnabled      pgtype.Bool        `json:"sso_enabled"`
	SamlMetadataUrl pgtype.Text        `json:"saml_metadata_url"`
	OidcIssuer      pgtype.Text        `json:"oidc_issuer"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Package struct {
	ID             uuid.UUID          `json:"id"`
	Name           string             `json:"name"`
	Namespace      pgtype.Text        `json:"namespace"`
	DisplayName    string             `json:"display_name"`
	Description    pgtype.Text        `json:"description"`
	Homepage       pgtype.Text        `json:"homepage"`
	Repository     pgtype.Text        `json:"repository"`
	License        pgtype.Text        `json:"license"`
	Keywords       []string           `json:"keywords"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	OwnerUserID    pgtype.UUID        `json:"owner_user_id"`
	OwnerOrgID     pgtype.UUID        `json:"owner_org_id"`
	Verified       pgtype.Bool        `json:"verified"`
	Trusted        pgtype.Bool        `json:"trusted"`
	TotalDownloads pgtype.Int8        `json:"total_downloads"`
	SearchVector   string             `json:"search_vector"`
}

type PackageFile struct {
	ID            uuid.UUID          `json:"id"`
	VersionID     uuid.UUID          `json:"version_id"`
	Filename      string             `json:"filename"`
	Filetype      string             `json:"filetype"`
	PythonVersion pgtype.Text        `json:"python_version"`
	Abi           pgtype.Text        `json:"abi"`
	Platform      pgtype.Text        `json:"platform"`
	SizeBytes     int64              `json:"size_bytes"`
	Sha256        string             `json:"sha256"`
	Md5           string             `json:"md5"`
	S3Key         string             `json:"s3_key"`
	DownloadCount pgtype.Int8        `json:"download_count"`
	UploadedAt    pgtype.Timestamptz `json:"uploaded_at"`
}

type PackageVersion struct {
	ID                 uuid.UUID          `json:"id"`
	PackageID          uuid.UUID          `json:"package_id"`
	Version            string             `json:"version"`
	RequiresPython     pgtype.Text        `json:"requires_python"`
	RequiresHivemind   pgtype.Text        `json:"requires_hivemind"`
	ToolCount          pgtype.Int4        `json:"tool_count"`
	UploadedBy         pgtype.UUID        `json:"uploaded_by"`
	UploadedAt         pgtype.Timestamptz `json:"uploaded_at"`
	Published          pgtype.Bool        `json:"published"`
	Yanked             pgtype.Bool        `json:"yanked"`
	YankReason         pgtype.Text        `json:"yank_reason"`
	VerificationStatus pgtype.Text        `json:"verification_status"`
	VerificationReport []byte             `json:"verification_report"`
	SigstoreBundle     []byte             `json:"sigstore_bundle"`
}

type RegistryProfile struct {
	UserID         string             `json:"user_id"`
	Username       string             `json:"username"`
	Bio            pgtype.Text        `json:"bio"`
	Website        pgtype.Text        `json:"website"`
	TotalPackages  pgtype.Int4        `json:"total_packages"`
	TotalDownloads pgtype.Int8        `json:"total_downloads"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID            uuid.UUID          `json:"id"`
	Email         string             `json:"email"`
	Username      string             `json:"username"`
	PasswordHash  pgtype.Text        `json:"password_hash"`
	EmailVerified pgtype.Bool        `json:"email_verified"`
	TotpSecret    pgtype.Text        `json:"totp_secret"`
	TotpEnabled   pgtype.Bool        `json:"totp_enabled"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	LastLoginAt   pgtype.Timestamptz `json:"last_login_at"`
	Banned        pgtype.Bool        `json:"banned"`
}
