// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addOrgMember = `-- name: AddOrgMember :one
INSERT INTO org_members (org_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING org_id, user_id, role
`

type AddOrgMemberParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	UserID uuid.UUID `json:"user_id"`
	Role   string    `json:"role"`
}

func (q *Queries) AddOrgMember(ctx context.Context, arg AddOrgMemberParams) (OrgMember, error) {
	row := q.db.QueryRow(ctx, addOrgMember, arg.OrgID, arg.UserID, arg.Role)
	var i OrgMember
	err := row.Scan(&i.OrgID, &i.UserID, &i.Role)
	return i, err
}

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (user_id, org_id, name, key_hash, key_prefix, scopes, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, org_id, name, key_hash, key_prefix, scopes, last_used_at, expires_at, created_at, revoked
`

type CreateAPIKeyParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	Name      string             `json:"name"`
	KeyHash   string             `json:"key_hash"`
	KeyPrefix string             `json:"key_prefix"`
	Scopes    []string           `json:"scopes"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.UserID,
		arg.OrgID,
		arg.Name,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.Scopes,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Scopes,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Revoked,
	)
	return i, err
}

const createDockerImage = `-- name: CreateDockerImage :one
INSERT INTO docker_images (package_id, tag, digest, ecr_uri, platform, size_bytes)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (package_id, tag) DO UPDATE SET digest = $3, ecr_uri = $4, platform = $5, size_bytes = $6, pushed_at = now()
RETURNING id, package_id, tag, digest, ecr_uri, platform, size_bytes, pushed_at
`

type CreateDockerImageParams struct {
	PackageID uuid.UUID   `json:"package_id"`
	Tag       string      `json:"tag"`
	Digest    string      `json:"digest"`
	EcrUri    string      `json:"ecr_uri"`
	Platform  []string    `json:"platform"`
	SizeBytes pgtype.Int8 `json:"size_bytes"`
}

func (q *Queries) CreateDockerImage(ctx context.Context, arg CreateDockerImageParams) (DockerImage, error) {
	row := q.db.QueryRow(ctx, createDockerImage,
		arg.PackageID,
		arg.Tag,
		arg.Digest,
		arg.EcrUri,
		arg.Platform,
		arg.SizeBytes,
	)
	var i DockerImage
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.Tag,
		&i.Digest,
		&i.EcrUri,
		&i.Platform,
		&i.SizeBytes,
		&i.PushedAt,
	)
	return i, err
}

const createOAuthIdentity = `-- name: CreateOAuthIdentity :one
INSERT INTO oauth_identities (user_id, provider, provider_user_id, provider_email)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, provider, provider_user_id, provider_email
`

type CreateOAuthIdentityParams struct {
	UserID         uuid.UUID   `json:"user_id"`
	Provider       string      `json:"provider"`
	ProviderUserID string      `json:"provider_user_id"`
	ProviderEmail  pgtype.Text `json:"provider_email"`
}

func (q *Queries) CreateOAuthIdentity(ctx context.Context, arg CreateOAuthIdentityParams) (OauthIdentity, error) {
	row := q.db.QueryRow(ctx, createOAuthIdentity,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.ProviderEmail,
	)
	var i OauthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.ProviderEmail,
	)
	return i, err
}

const createOrg = `-- name: CreateOrg :one
INSERT INTO organizations (name, display_name, billing_email)
VALUES ($1, $2, $3)
RETURNING id, name, display_name, billing_email, sso_enabled, saml_metadata_url, oidc_issuer, created_at
`

type CreateOrgParams struct {
	Name         string      `json:"name"`
	DisplayName  string      `json:"display_name"`
	BillingEmail pgtype.Text `json:"billing_email"`
}

func (q *Queries) CreateOrg(ctx context.Context, arg CreateOrgParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrg, arg.Name, arg.DisplayName, arg.BillingEmail)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.BillingEmail,
		&i.SsoEnabled,
		&i.SamlMetadataUrl,
		&i.OidcIssuer,
		&i.CreatedAt,
	)
	return i, err
}

const createPackage = `-- name: CreatePackage :one
INSERT INTO packages (name, namespace, display_name, description, homepage, repository, license, keywords, owner_user_id, owner_org_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, name, namespace, display_name, description, homepage, repository, license, keywords, created_at, owner_user_id, owner_org_id, verified, trusted, total_downloads, search_vector
`

type CreatePackageParams struct {
	Name        string      `json:"name"`
	Namespace   pgtype.Text `json:"namespace"`
	DisplayName string      `json:"display_name"`
	Description pgtype.Text `json:"description"`
	Homepage    pgtype.Text `json:"homepage"`
	Repository  pgtype.Text `json:"repository"`
	License     pgtype.Text `json:"license"`
	Keywords    []string    `json:"keywords"`
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
	OwnerOrgID  pgtype.UUID `json:"owner_org_id"`
}

func (q *Queries) CreatePackage(ctx context.Context, arg CreatePackageParams) (Package, error) {
	row := q.db.QueryRow(ctx, createPackage,
		arg.Name,
		arg.Namespace,
		arg.DisplayName,
		arg.Description,
		arg.Homepage,
		arg.Repository,
		arg.License,
		arg.Keywords,
		arg.OwnerUserID,
		arg.OwnerOrgID,
	)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Namespace,
		&i.DisplayName,
		&i.Description,
		&i.Homepage,
		&i.Repository,
		&i.License,
		&i.Keywords,
		&i.CreatedAt,
		&i.OwnerUserID,
		&i.OwnerOrgID,
		&i.Verified,
		&i.Trusted,
		&i.TotalDownloads,
		&i.SearchVector,
	)
	return i, err
}

const createPackageFile = `-- name: CreatePackageFile :one
INSERT INTO package_files (version_id, filename, filetype, python_version, abi, platform, size_bytes, sha256, md5, s3_key)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, version_id, filename, filetype, python_version, abi, platform, size_bytes, sha256, md5, s3_key, download_count, uploaded_at
`

type CreatePackageFileParams struct {
	VersionID     uuid.UUID   `json:"version_id"`
	Filename      string      `json:"filename"`
	Filetype      string      `json:"filetype"`
	PythonVersion pgtype.Text `json:"python_version"`
	Abi           pgtype.Text `json:"abi"`
	Platform      pgtype.Text `json:"platform"`
	SizeBytes     int64       `json:"size_bytes"`
	Sha256        string      `json:"sha256"`
	Md5           string      `json:"md5"`
	S3Key         string      `json:"s3_key"`
}

func (q *Queries) CreatePackageFile(ctx context.Context, arg CreatePackageFileParams) (PackageFile, error) {
	row := q.db.QueryRow(ctx, createPackageFile,
		arg.VersionID,
		arg.Filename,
		arg.Filetype,
		arg.PythonVersion,
		arg.Abi,
		arg.Platform,
		arg.SizeBytes,
		arg.Sha256,
		arg.Md5,
		arg.S3Key,
	)
	var i PackageFile
	err := row.Scan(
		&i.ID,
		&i.VersionID,
		&i.Filename,
		&i.Filetype,
		&i.PythonVersion,
		&i.Abi,
		&i.Platform,
		&i.SizeBytes,
		&i.Sha256,
		&i.Md5,
		&i.S3Key,
		&i.DownloadCount,
		&i.UploadedAt,
	)
	return i, err
}

const createPackageVersion = `-- name: CreatePackageVersion :one
INSERT INTO package_versions (package_id, version, requires_python, requires_hivemind, uploaded_by, verification_status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, package_id, version, requires_python, requires_hivemind, tool_count, uploaded_by, uploaded_at, published, yanked, yank_reason, verification_status, verification_report, sigstore_bundle
`

type CreatePackageVersionParams struct {
	PackageID          uuid.UUID   `json:"package_id"`
	Version            string      `json:"version"`
	RequiresPython     pgtype.Text `json:"requires_python"`
	RequiresHivemind   pgtype.Text `json:"requires_hivemind"`
	UploadedBy         pgtype.UUID `json:"uploaded_by"`
	VerificationStatus pgtype.Text `json:"verification_status"`
}

func (q *Queries) CreatePackageVersion(ctx context.Context, arg CreatePackageVersionParams) (PackageVersion, error) {
	row := q.db.QueryRow(ctx, createPackageVersion,
		arg.PackageID,
		arg.Version,
		arg.RequiresPython,
		arg.RequiresHivemind,
		arg.UploadedBy,
		arg.VerificationStatus,
	)
	var i PackageVersion
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.Version,
		&i.RequiresPython,
		&i.RequiresHivemind,
		&i.ToolCount,
		&i.UploadedBy,
		&i.UploadedAt,
		&i.Published,
		&i.Yanked,
		&i.YankReason,
		&i.VerificationStatus,
		&i.VerificationReport,
		&i.SigstoreBundle,
	)
	return i, err
}

const createRegistryProfile = `-- name: CreateRegistryProfile :one
INSERT INTO registry_profiles (user_id, username)
VALUES ($1, $2)
RETURNING user_id, username, bio, website, total_packages, total_downloads, created_at
`

type CreateRegistryProfileParams struct {
	UserID   string `json:"user_id"`
	Username string `json:"username"`
}

func (q *Queries) CreateRegistryProfile(ctx context.Context, arg CreateRegistryProfileParams) (RegistryProfile, error) {
	row := q.db.QueryRow(ctx, createRegistryProfile, arg.UserID, arg.Username)
	var i RegistryProfile
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Bio,
		&i.Website,
		&i.TotalPackages,
		&i.TotalDownloads,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, username, password_hash)
VALUES ($1, $2, $3)
RETURNING id, email, username, password_hash, email_verified, totp_secret, totp_enabled, created_at, last_login_at, banned
`

type CreateUserParams struct {
	Email        string      `json:"email"`
	Username     string      `json:"username"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Username, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.Banned,
	)
	return i, err
}

const deletePackage = `-- name: DeletePackage :exec
DELETE FROM packages WHERE id = $1
`

func (q *Queries) DeletePackage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePackage, id)
	return err
}

const deletePackageVersion = `-- name: DeletePackageVersion :exec
DELETE FROM package_versions WHERE id = $1
`

func (q *Queries) DeletePackageVersion(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePackageVersion, id)
	return err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, user_id, org_id, name, key_hash, key_prefix, scopes, last_used_at, expires_at, created_at, revoked FROM api_keys WHERE key_hash = $1 AND NOT revoked
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Scopes,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Revoked,
	)
	return i, err
}

const getGlobalStats = `-- name: GetGlobalStats :one
SELECT
  (SELECT count(*)::bigint FROM packages) as total_packages,
  (SELECT coalesce(sum(total_downloads), 0)::bigint FROM packages) as total_downloads
`

type GetGlobalStatsRow struct {
	TotalPackages  int64 `json:"total_packages"`
	TotalDownloads int64 `json:"total_downloads"`
}

func (q *Queries) GetGlobalStats(ctx context.Context) (GetGlobalStatsRow, error) {
	row := q.db.QueryRow(ctx, getGlobalStats)
	var i GetGlobalStatsRow
	err := row.Scan(&i.TotalPackages, &i.TotalDownloads)
	return i, err
}

const getOAuthIdentity = `-- name: GetOAuthIdentity :one
SELECT id, user_id, provider, provider_user_id, provider_email FROM oauth_identities WHERE provider = $1 AND provider_user_id = $2
`

type GetOAuthIdentityParams struct {
	Provider       string `json:"provider"`
	ProviderUserID string `json:"provider_user_id"`
}

func (q *Queries) GetOAuthIdentity(ctx context.Context, arg GetOAuthIdentityParams) (OauthIdentity, error) {
	row := q.db.QueryRow(ctx, getOAuthIdentity, arg.Provider, arg.ProviderUserID)
	var i OauthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.ProviderEmail,
	)
	return i, err
}

const getOrgByID = `-- name: GetOrgByID :one
SELECT id, name, display_name, billing_email, sso_enabled, saml_metadata_url, oidc_issuer, created_at FROM organizations WHERE id = $1
`

func (q *Queries) GetOrgByID(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrgByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.BillingEmail,
		&i.SsoEnabled,
		&i.SamlMetadataUrl,
		&i.OidcIssuer,
		&i.CreatedAt,
	)
	return i, err
}

const getOrgByName = `-- name: GetOrgByName :one
SELECT id, name, display_name, billing_email, sso_enabled, saml_metadata_url, oidc_issuer, created_at FROM organizations WHERE name = $1
`

func (q *Queries) GetOrgByName(ctx context.Context, name string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrgByName, name)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.BillingEmail,
		&i.SsoEnabled,
		&i.SamlMetadataUrl,
		&i.OidcIssuer,
		&i.CreatedAt,
	)
	return i, err
}

const getOrgMember = `-- name: GetOrgMember :one
SELECT org_id, user_id, role FROM org_members WHERE org_id = $1 AND user_id = $2
`

type GetOrgMemberParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetOrgMember(ctx context.Context, arg GetOrgMemberParams) (OrgMember, error) {
	row := q.db.QueryRow(ctx, getOrgMember, arg.OrgID, arg.UserID)
	var i OrgMember
	err := row.Scan(&i.OrgID, &i.UserID, &i.Role)
	return i, err
}

const getPackageByID = `-- name: GetPackageByID :one
SELECT id, name, namespace, display_name, description, homepage, repository, license, keywords, created_at, owner_user_id, owner_org_id, verified, trusted, total_downloads, search_vector FROM packages WHERE id = $1
`

func (q *Queries) GetPackageByID(ctx context.Context, id uuid.UUID) (Package, error) {
	row := q.db.QueryRow(ctx, getPackageByID, id)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Namespace,
		&i.DisplayName,
		&i.Description,
		&i.Homepage,
		&i.Repository,
		&i.License,
		&i.Keywords,
		&i.CreatedAt,
		&i.OwnerUserID,
		&i.OwnerOrgID,
		&i.Verified,
		&i.Trusted,
		&i.TotalDownloads,
		&i.SearchVector,
	)
	return i, err
}

const getPackageByNamespaceName = `-- name: GetPackageByNamespaceName :one
SELECT id, name, namespace, display_name, description, homepage, repository, license, keywords, created_at, owner_user_id, owner_org_id, verified, trusted, total_downloads, search_vector FROM packages WHERE (namespace IS NOT DISTINCT FROM $1) AND name = $2
`

type GetPackageByNamespaceNameParams struct {
	Namespace pgtype.Text `json:"namespace"`
	Name      string      `json:"name"`
}

func (q *Queries) GetPackageByNamespaceName(ctx context.Context, arg GetPackageByNamespaceNameParams) (Package, error) {
	row := q.db.QueryRow(ctx, getPackageByNamespaceName, arg.Namespace, arg.Name)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Namespace,
		&i.DisplayName,
		&i.Description,
		&i.Homepage,
		&i.Repository,
		&i.License,
		&i.Keywords,
		&i.CreatedAt,
		&i.OwnerUserID,
		&i.OwnerOrgID,
		&i.Verified,
		&i.Trusted,
		&i.TotalDownloads,
		&i.SearchVector,
	)
	return i, err
}

const getPackageFileByID = `-- name: GetPackageFileByID :one
SELECT id, version_id, filename, filetype, python_version, abi, platform, size_bytes, sha256, md5, s3_key, download_count, uploaded_at FROM package_files WHERE id = $1
`

func (q *Queries) GetPackageFileByID(ctx context.Context, id uuid.UUID) (PackageFile, error) {
	row := q.db.QueryRow(ctx, getPackageFileByID, id)
	var i PackageFile
	err := row.Scan(
		&i.ID,
		&i.VersionID,
		&i.Filename,
		&i.Filetype,
		&i.PythonVersion,
		&i.Abi,
		&i.Platform,
		&i.SizeBytes,
		&i.Sha256,
		&i.Md5,
		&i.S3Key,
		&i.DownloadCount,
		&i.UploadedAt,
	)
	return i, err
}

const getPackageFileByVersionAndFilename = `-- name: GetPackageFileByVersionAndFilename :one
SELECT id, version_id, filename, filetype, python_version, abi, platform, size_bytes, sha256, md5, s3_key, download_count, uploaded_at FROM package_files WHERE version_id = $1 AND filename = $2
`

type GetPackageFileByVersionAndFilenameParams struct {
	VersionID uuid.UUID `json:"version_id"`
	Filename  string    `json:"filename"`
}

func (q *Queries) GetPackageFileByVersionAndFilename(ctx context.Context, arg GetPackageFileByVersionAndFilenameParams) (PackageFile, error) {
	row := q.db.QueryRow(ctx, getPackageFileByVersionAndFilename, arg.VersionID, arg.Filename)
	var i PackageFile
	err := row.Scan(
		&i.ID,
		&i.VersionID,
		&i.Filename,
		&i.Filetype,
		&i.PythonVersion,
		&i.Abi,
		&i.Platform,
		&i.SizeBytes,
		&i.Sha256,
		&i.Md5,
		&i.S3Key,
		&i.DownloadCount,
		&i.UploadedAt,
	)
	return i, err
}

const getPackageVersion = `-- name: GetPackageVersion :one
SELECT pv.id, pv.package_id, pv.version, pv.requires_python, pv.requires_hivemind, pv.tool_count, pv.uploaded_by, pv.uploaded_at, pv.published, pv.yanked, pv.yank_reason, pv.verification_status, pv.verification_report, pv.sigstore_bundle FROM package_versions pv
JOIN packages p ON p.id = pv.package_id
WHERE (p.namespace IS NOT DISTINCT FROM $1) AND p.name = $2 AND pv.version = $3
`

type GetPackageVersionParams struct {
	Namespace pgtype.Text `json:"namespace"`
	Name      string      `json:"name"`
	Version   string      `json:"version"`
}

func (q *Queries) GetPackageVersion(ctx context.Context, arg GetPackageVersionParams) (PackageVersion, error) {
	row := q.db.QueryRow(ctx, getPackageVersion, arg.Namespace, arg.Name, arg.Version)
	var i PackageVersion
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.Version,
		&i.RequiresPython,
		&i.RequiresHivemind,
		&i.ToolCount,
		&i.UploadedBy,
		&i.UploadedAt,
		&i.Published,
		&i.Yanked,
		&i.YankReason,
		&i.VerificationStatus,
		&i.VerificationReport,
		&i.SigstoreBundle,
	)
	return i, err
}

const getRegistryProfileByUserID = `-- name: GetRegistryProfileByUserID :one
SELECT user_id, username, bio, website, total_packages, total_downloads, created_at FROM registry_profiles WHERE user_id = $1
`

func (q *Queries) GetRegistryProfileByUserID(ctx context.Context, userID string) (RegistryProfile, error) {
	row := q.db.QueryRow(ctx, getRegistryProfileByUserID, userID)
	var i RegistryProfile
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Bio,
		&i.Website,
		&i.TotalPackages,
		&i.TotalDownloads,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, password_hash, email_verified, totp_secret, totp_enabled, created_at, last_login_at, banned FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.Banned,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, username, password_hash, email_verified, totp_secret, totp_enabled, created_at, last_login_at, banned FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.Banned,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, email, username, password_hash, email_verified, totp_secret, totp_enabled, created_at, last_login_at, banned FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.Banned,
	)
	return i, err
}

const getVersionByID = `-- name: GetVersionByID :one
SELECT id, package_id, version, requires_python, requires_hivemind, tool_count, uploaded_by, uploaded_at, published, yanked, yank_reason, verification_status, verification_report, sigstore_bundle FROM package_versions WHERE id = $1
`

func (q *Queries) GetVersionByID(ctx context.Context, id uuid.UUID) (PackageVersion, error) {
	row := q.db.QueryRow(ctx, getVersionByID, id)
	var i PackageVersion
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.Version,
		&i.RequiresPython,
		&i.RequiresHivemind,
		&i.ToolCount,
		&i.UploadedBy,
		&i.UploadedAt,
		&i.Published,
		&i.Yanked,
		&i.YankReason,
		&i.VerificationStatus,
		&i.VerificationReport,
		&i.SigstoreBundle,
	)
	return i, err
}

const incrementFileDownloadCount = `-- name: IncrementFileDownloadCount :exec
UPDATE package_files SET download_count = download_count + 1 WHERE id = $1
`

func (q *Queries) IncrementFileDownloadCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementFileDownloadCount, id)
	return err
}

const incrementPackageDownloadCount = `-- name: IncrementPackageDownloadCount :exec
UPDATE packages SET total_downloads = total_downloads + 1 WHERE id = $1
`

func (q *Queries) IncrementPackageDownloadCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementPackageDownloadCount, id)
	return err
}

const insertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO audit_log (actor_user_id, actor_api_key_id, action, resource_type, resource_id, metadata, ip_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type InsertAuditLogParams struct {
	ActorUserID   pgtype.UUID `json:"actor_user_id"`
	ActorApiKeyID pgtype.UUID `json:"actor_api_key_id"`
	Action        string      `json:"action"`
	ResourceType  pgtype.Text `json:"resource_type"`
	ResourceID    pgtype.Text `json:"resource_id"`
	Metadata      []byte      `json:"metadata"`
	IpHash        pgtype.Text `json:"ip_hash"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.ActorUserID,
		arg.ActorApiKeyID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Metadata,
		arg.IpHash,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listAPIKeysForUser = `-- name: ListAPIKeysForUser :many
SELECT id, user_id, org_id, name, key_prefix, scopes, last_used_at, expires_at, created_at
FROM api_keys WHERE user_id = $1 AND NOT revoked
`

type ListAPIKeysForUserRow struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	OrgID      pgtype.UUID        `json:"org_id"`
	Name       string             `json:"name"`
	KeyPrefix  string             `json:"key_prefix"`
	Scopes     []string           `json:"scopes"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAPIKeysForUser(ctx context.Context, userID uuid.UUID) ([]ListAPIKeysForUserRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeysForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAPIKeysForUserRow
	for rows.Next() {
		var i ListAPIKeysForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrgID,
			&i.Name,
			&i.KeyPrefix,
			&i.Scopes,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDockerImagesForPackage = `-- name: ListDockerImagesForPackage :many
SELECT id, package_id, tag, digest, ecr_uri, platform, size_bytes, pushed_at FROM docker_images WHERE package_id = $1 ORDER BY pushed_at DESC
`

func (q *Queries) ListDockerImagesForPackage(ctx context.Context, packageID uuid.UUID) ([]DockerImage, error) {
	rows, err := q.db.Query(ctx, listDockerImagesForPackage, packageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DockerImage
	for rows.Next() {
		var i DockerImage
		if err := rows.Scan(
			&i.ID,
			&i.PackageID,
			&i.Tag,
			&i.Digest,
			&i.EcrUri,
			&i.Platform,
			&i.SizeBytes,
			&i.PushedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesForVersion = `-- name: ListFilesForVersion :many
SELECT id, version_id, filename, filetype, python_version, abi, platform, size_bytes, sha256, md5, s3_key, download_count, uploaded_at FROM package_files WHERE version_id = $1
`

func (q *Queries) ListFilesForVersion(ctx context.Context, versionID uuid.UUID) ([]PackageFile, error) {
	rows, err := q.db.Query(ctx, listFilesForVersion, versionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PackageFile
	for rows.Next() {
		var i PackageFile
		if err := rows.Scan(
			&i.ID,
			&i.VersionID,
			&i.Filename,
			&i.Filetype,
			&i.PythonVersion,
			&i.Abi,
			&i.Platform,
			&i.SizeBytes,
			&i.Sha256,
			&i.Md5,
			&i.S3Key,
			&i.DownloadCount,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgMembers = `-- name: ListOrgMembers :many
SELECT m.org_id, m.user_id, m.role, u.email, u.username
FROM org_members m
JOIN users u ON u.id = m.user_id
WHERE m.org_id = $1
`

type ListOrgMembersRow struct {
	OrgID    uuid.UUID `json:"org_id"`
	UserID   uuid.UUID `json:"user_id"`
	Role     string    `json:"role"`
	Email    string    `json:"email"`
	Username string    `json:"username"`
}

func (q *Queries) ListOrgMembers(ctx context.Context, orgID uuid.UUID) ([]ListOrgMembersRow, error) {
	rows, err := q.db.Query(ctx, listOrgMembers, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrgMembersRow
	for rows.Next() {
		var i ListOrgMembersRow
		if err := rows.Scan(
			&i.OrgID,
			&i.UserID,
			&i.Role,
			&i.Email,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgsForUser = `-- name: ListOrgsForUser :many
SELECT o.id, o.name, o.display_name, o.billing_email, o.sso_enabled, o.saml_metadata_url, o.oidc_issuer, o.created_at FROM organizations o
JOIN org_members m ON m.org_id = o.id
WHERE m.user_id = $1
`

func (q *Queries) ListOrgsForUser(ctx context.Context, userID uuid.UUID) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listOrgsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organization
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.BillingEmail,
			&i.SsoEnabled,
			&i.SamlMetadataUrl,
			&i.OidcIssuer,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackages = `-- name: ListPackages :many
SELECT id, name, namespace, display_name, description, homepage, repository, license, keywords, created_at, owner_user_id, owner_org_id, verified, trusted, total_downloads, search_vector FROM packages
WHERE ($1::text IS NULL OR namespace = $1)
ORDER BY name
LIMIT $3 OFFSET $2
`

type ListPackagesParams struct {
	NamespaceFilter pgtype.Text `json:"namespace_filter"`
	OffsetVal       int32       `json:"offset_val"`
	LimitVal        int32       `json:"limit_val"`
}

func (q *Queries) ListPackages(ctx context.Context, arg ListPackagesParams) ([]Package, error) {
	rows, err := q.db.Query(ctx, listPackages, arg.NamespaceFilter, arg.OffsetVal, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Package
	for rows.Next() {
		var i Package
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Namespace,
			&i.DisplayName,
			&i.Description,
			&i.Homepage,
			&i.Repository,
			&i.License,
			&i.Keywords,
			&i.CreatedAt,
			&i.OwnerUserID,
			&i.OwnerOrgID,
			&i.Verified,
			&i.Trusted,
			&i.TotalDownloads,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingVerifications = `-- name: ListPendingVerifications :many
SELECT pv.id, pv.package_id, pv.version, pv.requires_python, pv.requires_hivemind, pv.tool_count, pv.uploaded_by, pv.uploaded_at, pv.published, pv.yanked, pv.yank_reason, pv.verification_status, pv.verification_report, pv.sigstore_bundle, p.name as package_name, p.namespace
FROM package_versions pv
JOIN packages p ON p.id = pv.package_id
WHERE pv.verification_status = 'pending'
ORDER BY pv.uploaded_at
LIMIT $1
`

type ListPendingVerificationsRow struct {
	ID                 uuid.UUID          `json:"id"`
	PackageID          uuid.UUID          `json:"package_id"`
	Version            string             `json:"version"`
	RequiresPython     pgtype.Text        `json:"requires_python"`
	RequiresHivemind   pgtype.Text        `json:"requires_hivemind"`
	ToolCount          pgtype.Int4        `json:"tool_count"`
	UploadedBy         pgtype.UUID        `json:"uploaded_by"`
	UploadedAt         pgtype.Timestamptz `json:"uploaded_at"`
	Published          pgtype.Bool        `json:"published"`
	Yanked             pgtype.Bool        `json:"yanked"`
	YankReason         pgtype.Text        `json:"yank_reason"`
	VerificationStatus pgtype.Text        `json:"verification_status"`
	VerificationReport []byte             `json:"verification_report"`
	SigstoreBundle     []byte             `json:"sigstore_bundle"`
	PackageName        string             `json:"package_name"`
	Namespace          pgtype.Text        `json:"namespace"`
}

func (q *Queries) ListPendingVerifications(ctx context.Context, limit int32) ([]ListPendingVerificationsRow, error) {
	rows, err := q.db.Query(ctx, listPendingVerifications, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingVerificationsRow
	for rows.Next() {
		var i ListPendingVerificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.PackageID,
			&i.Version,
			&i.RequiresPython,
			&i.RequiresHivemind,
			&i.ToolCount,
			&i.UploadedBy,
			&i.UploadedAt,
			&i.Published,
			&i.Yanked,
			&i.YankReason,
			&i.VerificationStatus,
			&i.VerificationReport,
			&i.SigstoreBundle,
			&i.PackageName,
			&i.Namespace,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersAdmin = `-- name: ListUsersAdmin :many
SELECT id, email, username, email_verified, created_at, last_login_at, banned
FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersAdminParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUsersAdminRow struct {
	ID            uuid.UUID          `json:"id"`
	Email         string             `json:"email"`
	Username      string             `json:"username"`
	EmailVerified pgtype.Bool        `json:"email_verified"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	LastLoginAt   pgtype.Timestamptz `json:"last_login_at"`
	Banned        pgtype.Bool        `json:"banned"`
}

func (q *Queries) ListUsersAdmin(ctx context.Context, arg ListUsersAdminParams) ([]ListUsersAdminRow, error) {
	rows, err := q.db.Query(ctx, listUsersAdmin, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersAdminRow
	for rows.Next() {
		var i ListUsersAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.EmailVerified,
			&i.CreatedAt,
			&i.LastLoginAt,
			&i.Banned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVersionsForPackage = `-- name: ListVersionsForPackage :many
SELECT id, package_id, version, requires_python, requires_hivemind, tool_count, uploaded_by, uploaded_at, published, yanked, yank_reason, verification_status, verification_report, sigstore_bundle FROM package_versions WHERE package_id = $1 ORDER BY uploaded_at DESC
`

func (q *Queries) ListVersionsForPackage(ctx context.Context, packageID uuid.UUID) ([]PackageVersion, error) {
	rows, err := q.db.Query(ctx, listVersionsForPackage, packageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PackageVersion
	for rows.Next() {
		var i PackageVersion
		if err := rows.Scan(
			&i.ID,
			&i.PackageID,
			&i.Version,
			&i.RequiresPython,
			&i.RequiresHivemind,
			&i.ToolCount,
			&i.UploadedBy,
			&i.UploadedAt,
			&i.Published,
			&i.Yanked,
			&i.YankReason,
			&i.VerificationStatus,
			&i.VerificationReport,
			&i.SigstoreBundle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordDownloadEvent = `-- name: RecordDownloadEvent :one
INSERT INTO download_events (file_id, ip_hash, user_agent, country_code, installer)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type RecordDownloadEventParams struct {
	FileID      uuid.UUID   `json:"file_id"`
	IpHash      pgtype.Text `json:"ip_hash"`
	UserAgent   pgtype.Text `json:"user_agent"`
	CountryCode pgtype.Text `json:"country_code"`
	Installer   pgtype.Text `json:"installer"`
}

func (q *Queries) RecordDownloadEvent(ctx context.Context, arg RecordDownloadEventParams) (pgtype.Int8, error) {
	row := q.db.QueryRow(ctx, recordDownloadEvent,
		arg.FileID,
		arg.IpHash,
		arg.UserAgent,
		arg.CountryCode,
		arg.Installer,
	)
	var id pgtype.Int8
	err := row.Scan(&id)
	return id, err
}

const removeOrgMember = `-- name: RemoveOrgMember :exec
DELETE FROM org_members WHERE org_id = $1 AND user_id = $2
`

type RemoveOrgMemberParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveOrgMember(ctx context.Context, arg RemoveOrgMemberParams) error {
	_, err := q.db.Exec(ctx, removeOrgMember, arg.OrgID, arg.UserID)
	return err
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE api_keys SET revoked = true WHERE id = $1
`

func (q *Queries) RevokeAPIKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAPIKey, id)
	return err
}

const searchPackages = `-- name: SearchPackages :many
SELECT id, name, namespace, display_name, description, homepage, repository, license, keywords, created_at, owner_user_id, owner_org_id, verified, trusted, total_downloads, search_vector FROM packages
WHERE search_vector @@ plainto_tsquery('english', $1)
ORDER BY ts_rank(search_vector, plainto_tsquery('english', $1)) DESC
LIMIT $2 OFFSET $3
`

type SearchPackagesParams struct {
	PlaintoTsquery string `json:"plainto_tsquery"`
	Limit          int32  `json:"limit"`
	Offset         int32  `json:"offset"`
}

func (q *Queries) SearchPackages(ctx context.Context, arg SearchPackagesParams) ([]Package, error) {
	rows, err := q.db.Query(ctx, searchPackages, arg.PlaintoTsquery, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Package
	for rows.Next() {
		var i Package
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Namespace,
			&i.DisplayName,
			&i.Description,
			&i.Homepage,
			&i.Repository,
			&i.License,
			&i.Keywords,
			&i.CreatedAt,
			&i.OwnerUserID,
			&i.OwnerOrgID,
			&i.Verified,
			&i.Trusted,
			&i.TotalDownloads,
			&i.SearchVector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPackageTrusted = `-- name: SetPackageTrusted :one
UPDATE packages SET trusted = true WHERE id = $1
RETURNING id, name, namespace, display_name, description, homepage, repository, license, keywords, created_at, owner_user_id, owner_org_id, verified, trusted, total_downloads, search_vector
`

func (q *Queries) SetPackageTrusted(ctx context.Context, id uuid.UUID) (Package, error) {
	row := q.db.QueryRow(ctx, setPackageTrusted, id)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Namespace,
		&i.DisplayName,
		&i.Description,
		&i.Homepage,
		&i.Repository,
		&i.License,
		&i.Keywords,
		&i.CreatedAt,
		&i.OwnerUserID,
		&i.OwnerOrgID,
		&i.Verified,
		&i.Trusted,
		&i.TotalDownloads,
		&i.SearchVector,
	)
	return i, err
}

const setUserBanned = `-- name: SetUserBanned :exec
UPDATE users SET banned = true WHERE id = $1
`

func (q *Queries) SetUserBanned(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setUserBanned, id)
	return err
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :exec
UPDATE api_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateAPIKeyLastUsed, id)
	return err
}

const updateOrg = `-- name: UpdateOrg :one
UPDATE organizations SET display_name = $2, billing_email = $3, sso_enabled = $4,
  saml_metadata_url = $5, oidc_issuer = $6
WHERE id = $1
RETURNING id, name, display_name, billing_email, sso_enabled, saml_metadata_url, oidc_issuer, created_at
`

type UpdateOrgParams struct {
	ID              uuid.UUID   `json:"id"`
	DisplayName     string      `json:"display_name"`
	BillingEmail    pgtype.Text `json:"billing_email"`
	SsoEnabled      pgtype.Bool `json:"sso_enabled"`
	SamlMetadataUrl pgtype.Text `json:"saml_metadata_url"`
	OidcIssuer      pgtype.Text `json:"oidc_issuer"`
}

func (q *Queries) UpdateOrg(ctx context.Context, arg UpdateOrgParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrg,
		arg.ID,
		arg.DisplayName,
		arg.BillingEmail,
		arg.SsoEnabled,
		arg.SamlMetadataUrl,
		arg.OidcIssuer,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.BillingEmail,
		&i.SsoEnabled,
		&i.SamlMetadataUrl,
		&i.OidcIssuer,
		&i.CreatedAt,
	)
	return i, err
}

const updateOrgMemberRole = `-- name: UpdateOrgMemberRole :one
UPDATE org_members SET role = $3 WHERE org_id = $1 AND user_id = $2
RETURNING org_id, user_id, role
`

type UpdateOrgMemberRoleParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	UserID uuid.UUID `json:"user_id"`
	Role   string    `json:"role"`
}

func (q *Queries) UpdateOrgMemberRole(ctx context.Context, arg UpdateOrgMemberRoleParams) (OrgMember, error) {
	row := q.db.QueryRow(ctx, updateOrgMemberRole, arg.OrgID, arg.UserID, arg.Role)
	var i OrgMember
	err := row.Scan(&i.OrgID, &i.UserID, &i.Role)
	return i, err
}

const updatePackage = `-- name: UpdatePackage :one
UPDATE packages SET display_name = $2, description = $3, homepage = $4, repository = $5, license = $6, keywords = $7, verified = $8, trusted = $9
WHERE id = $1
RETURNING id, name, namespace, display_name, description, homepage, repository, license, keywords, created_at, owner_user_id, owner_org_id, verified, trusted, total_downloads, search_vector
`

type UpdatePackageParams struct {
	ID          uuid.UUID   `json:"id"`
	DisplayName string      `json:"display_name"`
	Description pgtype.Text `json:"description"`
	Homepage    pgtype.Text `json:"homepage"`
	Repository  pgtype.Text `json:"repository"`
	License     pgtype.Text `json:"license"`
	Keywords    []string    `json:"keywords"`
	Verified    pgtype.Bool `json:"verified"`
	Trusted     pgtype.Bool `json:"trusted"`
}

func (q *Queries) UpdatePackage(ctx context.Context, arg UpdatePackageParams) (Package, error) {
	row := q.db.QueryRow(ctx, updatePackage,
		arg.ID,
		arg.DisplayName,
		arg.Description,
		arg.Homepage,
		arg.Repository,
		arg.License,
		arg.Keywords,
		arg.Verified,
		arg.Trusted,
	)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Namespace,
		&i.DisplayName,
		&i.Description,
		&i.Homepage,
		&i.Repository,
		&i.License,
		&i.Keywords,
		&i.CreatedAt,
		&i.OwnerUserID,
		&i.OwnerOrgID,
		&i.Verified,
		&i.Trusted,
		&i.TotalDownloads,
		&i.SearchVector,
	)
	return i, err
}

const updatePackageVersionVerification = `-- name: UpdatePackageVersionVerification :one
UPDATE package_versions SET verification_status = $2, verification_report = $3, published = $4, tool_count = $5, sigstore_bundle = $6
WHERE id = $1
RETURNING id, package_id, version, requires_python, requires_hivemind, tool_count, uploaded_by, uploaded_at, published, yanked, yank_reason, verification_status, verification_report, sigstore_bundle
`

type UpdatePackageVersionVerificationParams struct {
	ID                 uuid.UUID   `json:"id"`
	VerificationStatus pgtype.Text `json:"verification_status"`
	VerificationReport []byte      `json:"verification_report"`
	Published          pgtype.Bool `json:"published"`
	ToolCount          pgtype.Int4 `json:"tool_count"`
	SigstoreBundle     []byte      `json:"sigstore_bundle"`
}

func (q *Queries) UpdatePackageVersionVerification(ctx context.Context, arg UpdatePackageVersionVerificationParams) (PackageVersion, error) {
	row := q.db.QueryRow(ctx, updatePackageVersionVerification,
		arg.ID,
		arg.VerificationStatus,
		arg.VerificationReport,
		arg.Published,
		arg.ToolCount,
		arg.SigstoreBundle,
	)
	var i PackageVersion
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.Version,
		&i.RequiresPython,
		&i.RequiresHivemind,
		&i.ToolCount,
		&i.UploadedBy,
		&i.UploadedAt,
		&i.Published,
		&i.Yanked,
		&i.YankReason,
		&i.VerificationStatus,
		&i.VerificationReport,
		&i.SigstoreBundle,
	)
	return i, err
}

const updateRegistryProfile = `-- name: UpdateRegistryProfile :one
UPDATE registry_profiles SET username = $2, bio = $3, website = $4
WHERE user_id = $1
RETURNING user_id, username, bio, website, total_packages, total_downloads, created_at
`

type UpdateRegistryProfileParams struct {
	UserID   string      `json:"user_id"`
	Username string      `json:"username"`
	Bio      pgtype.Text `json:"bio"`
	Website  pgtype.Text `json:"website"`
}

func (q *Queries) UpdateRegistryProfile(ctx context.Context, arg UpdateRegistryProfileParams) (RegistryProfile, error) {
	row := q.db.QueryRow(ctx, updateRegistryProfile,
		arg.UserID,
		arg.Username,
		arg.Bio,
		arg.Website,
	)
	var i RegistryProfile
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Bio,
		&i.Website,
		&i.TotalPackages,
		&i.TotalDownloads,
		&i.CreatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET email = $2, username = $3, password_hash = $4, email_verified = $5,
  totp_secret = $6, totp_enabled = $7, last_login_at = $8, banned = $9
WHERE id = $1
RETURNING id, email, username, password_hash, email_verified, totp_secret, totp_enabled, created_at, last_login_at, banned
`

type UpdateUserParams struct {
	ID            uuid.UUID          `json:"id"`
	Email         string             `json:"email"`
	Username      string             `json:"username"`
	PasswordHash  pgtype.Text        `json:"password_hash"`
	EmailVerified pgtype.Bool        `json:"email_verified"`
	TotpSecret    pgtype.Text        `json:"totp_secret"`
	TotpEnabled   pgtype.Bool        `json:"totp_enabled"`
	LastLoginAt   pgtype.Timestamptz `json:"last_login_at"`
	Banned        pgtype.Bool        `json:"banned"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.EmailVerified,
		arg.TotpSecret,
		arg.TotpEnabled,
		arg.LastLoginAt,
		arg.Banned,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.Banned,
	)
	return i, err
}

const yankPackageVersion = `-- name: YankPackageVersion :one
UPDATE package_versions SET yanked = true, yank_reason = $2 WHERE id = $1
RETURNING id, package_id, version, requires_python, requires_hivemind, tool_count, uploaded_by, uploaded_at, published, yanked, yank_reason, verification_status, verification_report, sigstore_bundle
`

type YankPackageVersionParams struct {
	ID         uuid.UUID   `json:"id"`
	YankReason pgtype.Text `json:"yank_reason"`
}

func (q *Queries) YankPackageVersion(ctx context.Context, arg YankPackageVersionParams) (PackageVersion, error) {
	row := q.db.QueryRow(ctx, yankPackageVersion, arg.ID, arg.YankReason)
	var i PackageVersion
	err := row.Scan(
		&i.ID,
		&i.PackageID,
		&i.Version,
		&i.RequiresPython,
		&i.RequiresHivemind,
		&i.ToolCount,
		&i.UploadedBy,
		&i.UploadedAt,
		&i.Published,
		&i.Yanked,
		&i.YankReason,
		&i.VerificationStatus,
		&i.VerificationReport,
		&i.SigstoreBundle,
	)
	return i, err
}
