// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddOrgMember(ctx context.Context, arg AddOrgMemberParams) (OrgMember, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateDockerImage(ctx context.Context, arg CreateDockerImageParams) (DockerImage, error)
	CreateOAuthIdentity(ctx context.Context, arg CreateOAuthIdentityParams) (OauthIdentity, error)
	CreateOrg(ctx context.Context, arg CreateOrgParams) (Organization, error)
	CreatePackage(ctx context.Context, arg CreatePackageParams) (Package, error)
	CreatePackageFile(ctx context.Context, arg CreatePackageFileParams) (PackageFile, error)
	CreatePackageVersion(ctx context.Context, arg CreatePackageVersionParams) (PackageVersion, error)
	CreateRegistryProfile(ctx context.Context, arg CreateRegistryProfileParams) (RegistryProfile, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeletePackage(ctx context.Context, id uuid.UUID) error
	DeletePackageVersion(ctx context.Context, id uuid.UUID) error
	GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error)
	GetGlobalStats(ctx context.Context) (GetGlobalStatsRow, error)
	GetOAuthIdentity(ctx context.Context, arg GetOAuthIdentityParams) (OauthIdentity, error)
	GetOrgByID(ctx context.Context, id uuid.UUID) (Organization, error)
	GetOrgByName(ctx context.Context, name string) (Organization, error)
	GetOrgMember(ctx context.Context, arg GetOrgMemberParams) (OrgMember, error)
	GetPackageByID(ctx context.Context, id uuid.UUID) (Package, error)
	GetPackageByNamespaceName(ctx context.Context, arg GetPackageByNamespaceNameParams) (Package, error)
	GetPackageFileByID(ctx context.Context, id uuid.UUID) (PackageFile, error)
	GetPackageFileByVersionAndFilename(ctx context.Context, arg GetPackageFileByVersionAndFilenameParams) (PackageFile, error)
	GetPackageVersion(ctx context.Context, arg GetPackageVersionParams) (PackageVersion, error)
	GetRegistryProfileByUserID(ctx context.Context, userID string) (RegistryProfile, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetVersionByID(ctx context.Context, id uuid.UUID) (PackageVersion, error)
	IncrementFileDownloadCount(ctx context.Context, id uuid.UUID) error
	IncrementPackageDownloadCount(ctx context.Context, id uuid.UUID) error
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (int64, error)
	ListAPIKeysForUser(ctx context.Context, userID uuid.UUID) ([]ListAPIKeysForUserRow, error)
	ListDockerImagesForPackage(ctx context.Context, packageID uuid.UUID) ([]DockerImage, error)
	ListFilesForVersion(ctx context.Context, versionID uuid.UUID) ([]PackageFile, error)
	ListOrgMembers(ctx context.Context, orgID uuid.UUID) ([]ListOrgMembersRow, error)
	ListOrgsForUser(ctx context.Context, userID uuid.UUID) ([]Organization, error)
	ListPackages(ctx context.Context, arg ListPackagesParams) ([]Package, error)
	ListPendingVerifications(ctx context.Context, limit int32) ([]ListPendingVerificationsRow, error)
	ListUsersAdmin(ctx context.Context, arg ListUsersAdminParams) ([]ListUsersAdminRow, error)
	ListVersionsForPackage(ctx context.Context, packageID uuid.UUID) ([]PackageVersion, error)
	RecordDownloadEvent(ctx context.Context, arg RecordDownloadEventParams) (pgtype.Int8, error)
	RemoveOrgMember(ctx context.Context, arg RemoveOrgMemberParams) error
	RevokeAPIKey(ctx context.Context, id uuid.UUID) error
	SearchPackages(ctx context.Context, arg SearchPackagesParams) ([]Package, error)
	SetPackageTrusted(ctx context.Context, id uuid.UUID) (Package, error)
	SetUserBanned(ctx context.Context, id uuid.UUID) error
	UpdateAPIKeyLastUsed(ctx context.Context, id uuid.UUID) error
	UpdateOrg(ctx context.Context, arg UpdateOrgParams) (Organization, error)
	UpdateOrgMemberRole(ctx context.Context, arg UpdateOrgMemberRoleParams) (OrgMember, error)
	UpdatePackage(ctx context.Context, arg UpdatePackageParams) (Package, error)
	UpdatePackageVersionVerification(ctx context.Context, arg UpdatePackageVersionVerificationParams) (PackageVersion, error)
	UpdateRegistryProfile(ctx context.Context, arg UpdateRegistryProfileParams) (RegistryProfile, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	YankPackageVersion(ctx context.Context, arg YankPackageVersionParams) (PackageVersion, error)
}

var _ Querier = (*Queries)(nil)
